version: "3"

services:
  backend:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
      - "${DOCKER_STATIC_HOSTING}:/var/www/static"
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - proxy
    command: npm start

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
